dist: trusty
language: node_js
node_js:
  - '7.9.0'
services:
  - postgresql
jdk:
  - oraclejdk8
env:
  - WEBSERVICE_VERSION="1.2.0"
addons:
  firefox: "latest"
  postgresql: "9.4"
  chrome: stable
  chrome: beta

install:
  - 'npm install -g bower'
  - 'npm install'
  - 'bower update'
  - 'ng version'

before_script:
  - pwd
  - wget https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/2.3.0-SNAPSHOT/swagger-codegen-cli-2.3.0-20170715.005519-26.jar -O swagger-codegen-cli.jar
  - java -jar swagger-codegen-cli.jar generate -i https://raw.githubusercontent.com/ga4gh/dockstore/1.2.5/dockstore-webservice/src/main/resources/swagger.yaml -l typescript-angular -o src/app/shared/swagger


  - ./script
  - npm run-script prebuild
  - ng lint
script:
  - ng build # this does syntax checking, unit testing, and jshint

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f1c48703628e3514bb6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
