sudo: required
dist: trusty
language: node_js
node_js:
  - '7.9.0'
services:
  - postgresql
jdk:
  - oraclejdk8
env:
  - WEBSERVICE_VERSION="1.2.0-beta.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  firefox: "latest"
  postgresql: "9.4"
  chrome: stable
  chrome: beta

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - 'wget --tries=10 https://github.com/ga4gh/dockstore/releases/download/${WEBSERVICE_VERSION}/dockstore-webservice-${WEBSERVICE_VERSION}.jar'
  - 'chmod u+x dockstore-webservice-${WEBSERVICE_VERSION}.jar'
  - 'sleep 3' # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

install:
  - 'npm install -g bower'
  - 'npm install'
  - 'bower update'
  - 'ng version'
  - 'npm install codecov'

before_script:
  - pwd
  - wget https://artifacts.oicr.on.ca/artifactory/collab-release/io/swagger/swagger-codegen-cli/2.3.0-SNAPSHOT/swagger-codegen-cli-2.3.0-20170927.194112-1.jar -O swagger-codegen-cli.jar
  - java -jar swagger-codegen-cli.jar generate -i https://raw.githubusercontent.com/ga4gh/dockstore/1.2.5/dockstore-webservice/src/main/resources/swagger.yaml -l typescript-angular -o src/app/shared/swagger -c swagger-config.json
  - ./script
  - npm run-script prebuild
  - ng lint
  - psql 'postgres' -U postgres < travisci/db_dump.sql
  - java -jar dockstore-webservice-${WEBSERVICE_VERSION}.jar server travisci/web.yml 1>/dev/null &
  - 'sleep 20'

script:
  - ng build --environment=qa # this does syntax checking, unit testing, and jshint
  - ng serve --environment=qa --silent &
  - ng test --environment=qa --watch=false --code-coverage
  - cypress run --record --config defaultCommandTimeout=10000 #test using cypress for integration testing

after_success:
  - ./node_modules/codecov/bin/codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f1c48703628e3514bb6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
