sudo: required
dist: trusty
language: node_js
node_js:
  - '10.13.0'
services:
  - postgresql
jdk:
  - oraclejdk8
cache:
  npm: true # this caches ~/.npm folder on Travis
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
env:
  global:
    - WEBSERVICE_VERSION="1.6.0-beta.0"
addons:
  firefox: "latest"
  postgresql: "9.6"
  chrome: stable

install:
  - ./scripts/install-travis-script.sh

jobs:
  include:
    - stage: test
      script:
        - ng lint
        - ng test --watch=false --code-coverage --browsers ChromeHeadless
        - ng version
        - npm run build.prod
      env:
        - NAME='Lint, Unit Test, and Prod Test'
    - stage: test
      env:
        - NAME='Integration test 1'
        - TEST='cypress/integration/group1/**/*'
      script: ./scripts/run-travis-script.sh

    - stage: test
      env:
        - NAME='Integration test 2'
        - TEST='cypress/integration/group2/**/*'
      script: ./scripts/run-travis-script.sh

    - stage: test
      env:
        - NAME='Integration test 3'
        - TEST='cypress/integration/group3/**/*'
      script: ./scripts/run-travis-script.sh

script: echo "overriding test"

after_success:
  - ./node_modules/codecov/bin/codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f1c48703628e3514bb6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

