dist: trusty
language: node_js
node_js:
  - '7.9.0'
services:
  - postgresql
jdk:
  - oraclejdk8
env:
  - WEBSERVICE_VERSION="1.2.0"
addons:
  firefox: "latest"
  postgresql: "9.4"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta

install:
  - 'npm install -g bower'
  - 'npm install -g @angular/cli@latest'
  - 'npm install'
  - 'bower update'
  - 'ng version'

before_script:
  - ng build # this does syntax checking, unit testing, and jshint

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f1c48703628e3514bb6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
